

name: Build APK
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get Date
        id: get-date
        run: |
          echo "date=$(date -u +'%Y%m%d')" >> $GITHUB_OUTPUT
        shell: bash

      - name: Build with Buildozer
        uses: ArtemSerebriakov/buildozer-action@v1
        id: buildozer
        with:
          buildozer_version: master
          command: buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: dotto-app-debug-${{ steps.get-date.outputs.date }}
          path: bin/*.apk
